spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: admin
    password: securepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

camel:
  component:
    kafka:
      brokers: localhost:9092
